### ISSUE TITLE
Malfunctions in Windows

### ISSUE THREAD

**Issue by Adreitz** [MegaByte/jpegultrascan#2]
Hi, Megabyte. I've been using this program in OS X and think it's a great experimental tool for compressing JPEGs. I'd like to use it in Windows, too, but I can't get it to work properly.

I'm using the official release of jpegtran as well as the mozjpeg 3.2 version of jpegtran. Neither are in my PATH, so I specify the full path to each executable in the -p and -o variables. In this configuration, pretty much any JPEG I throw at it will produce an error message like "Corrupt JPEG data: premature end of data segment" or "Corrupt JPEG data: XXXX extraneous bytes before marker 0xc4" after almost every "tick" (period) on the command line output. In addition, the program dumps tons of temporary files of various sizes (from 0 KB up to almost the full size of the image) in the %USER%\AppData\Local\Temp folder, which can quickly eat up hard drive space. If I ignore the error messages and wait for the program to finish, the output file exists and is recognizable as the input image, but contains strange high-frequency noise that is most noticeable in dark areas of the image.

If I instead use standard jpegtran for both the -p and -o flags, it usually suppresses the error messages and prevents most, but not all, of the corrupt output, but I still get the temp files.

I've attached three images to demonstrate what I'm seeing -- the original file, the jpegultrascan output using both standard jpegtran and the mozjpeg version, and the output using only standard jpegtran. The standard-only file doesn't have any very obvious corruption in this example (I don't have an image comparison program available right now), but the fact that it sometimes produces corrupt output even using only standard jpegtran makes me hesitant to use jpegultrascan.

Original:
![original](https://cloud.githubusercontent.com/assets/11577741/24460119/4f5f0160-146b-11e7-98e7-20c111d0ffac.jpg)
Standard-only:
![ultra_stdonly](https://cloud.githubusercontent.com/assets/11577741/24460117/4f3bb1a6-146b-11e7-913e-95effc4d1562.jpg)
Standard+Mozjpeg:
![ultra_std moz](https://cloud.githubusercontent.com/assets/11577741/24460116/4f39c33c-146b-11e7-8bca-9b9c63f8e6e2.jpg)

I've been running jpegultrascan with Strawberry Perl 5.24.1.1 in Windows 7 32-bit.

Let me know if you have any questions.

Thanks!

Aaron Reitz

**Comment by MegaByte** [comment]
@Adreitz I believe I resolved the temp file situation, but I'll check the other issue when I can. Please provide a link to the particular jpegtran binaries you're using if you can.

**Comment by Adreitz** [comment]
@MegaByte Thanks for taking the time to look at this! Sorry it took me so long to get back to you. I downloaded the new .pl file and tried it on a random JPEG I downloaded, and it seemed to work fine. My happiness was short-lived, however, when retrying the image I previously attached. I got the same errors I received in the past (Corrupt JPEG data: 5556 extraneous bytes before marker 0xc4). I then tried it on the same image pre-optimized by pingo (https://css-ig.net/pingo) with the same results, and a couple other images I had lying around, which gave new error messages, but errors nonetheless: "Corrupt JPEG data: premature end of data segment" and "No data returned for:" followed by a scan setup. Pulling the file that worked back out of the Recycle Bin, it again seemed to work when I reprocessed it.

I'm now on Strawberry Perl 5.32.1.1 in Windows 10 64-bit, run with the following command:

perl C:\Users\[PATH]\jpegultrascan-master\jpegultrascan.pl -i -t 3 -b 9 -p C:\Users\[PATH]\jpegultrascan-master\jpegtran.exe -o C:\Users\[PATH]\jpegultrascan-master\mozjpegtran4.0.exe <inputfile> <outputfile>

I'll try to attach the two jpegtran versions I'm using in a separate reply, as I don't know if github will accept them.

Thanks again,

Aaron Reitz

**Comment by Adreitz** [comment]
Here are the binaries I'm using.
[binaries.zip](https://github.com/MegaByte/jpegultrascan/files/6142368/binaries.zip)

**Comment by MegaByte** [comment]
Thanks @Adreitz. Can you also let me know where the binaries came from? Did you build them yourself or can you give me download URLs?

**Comment by MegaByte** [comment]
I think this is fixed. Let me know if it doesn't work for you.

**Comment by Adreitz** [comment]
Thanks, @MegaByte. I have not tested very much, but -b 3 seemed to work with the image I attached previously. However, I then tried -b 13 and started to receive errors like:

No data returned for:
0 1 2: 0 0 0 9;
0: 45 47 10 9;
0: 45 47 9 8;
0: 45 47 8 7;
0: 45 47 7 6;
0: 45 47 6 5;
0: 45 47 5 4;
0: 45 47 4 3;
0: 45 47 3 2;
0: 45 47 2 1;
0: 45 47 1 0;
0: 48 50 0 10;
0: 48 50 10 9;
0: 48 50 9 8;
0: 48 50 8 7;
0: 48 50 7 6;
0: 48 50 6 5;
0: 48 50 5 4;
0: 48 50 4 3;
0: 48 50 3 2;
0: 48 50 2 1;
0: 48 50 1 0;
0: 51 53 0 10;
0: 51 53 10 9;
0: 51 53 9 8;
0: 51 53 8 7;
0: 51 53 7 6;
0: 51 53 6 5;
0: 51 53 5 4;
0: 51 53 4 3;
0: 51 53 3 2;
0: 51 53 2 1;
0: 51 53 1 0;
0: 54 56 0 10;
0: 54 56 10 9;
0: 54 56 9 8;
0: 54 56 8 7;
0: 54 56 7 6;
0: 54 56 6 5;
0: 54 56 5 4;
0: 54 56 4 3;
0: 54 56 3 2;
0: 54 56 2 1;
0: 54 56 1 0;
0: 57 59 0 10;
0: 57 59 10 9;
0: 57 59 9 8;
0: 57 59 8 7;
0: 57 59 7 6;
0: 57 59 6 5;
0: 57 59 5 4;
0: 57 59 4 3;
0: 57 59 3 2;
0: 57 59 2 1;
0: 57 59 1 0;
0: 60 62 0 10;
Invalid progressive parameters at scan script entry 2

This doesn't happen as often, with somewhere between 10 and 45 successful "ticks" before another error. I need to do more testing to see how common this is.

I downloaded the mozjpegtran binary from https://mozjpeg.codelove.de/binaries.html. The standard jpegtran binary is old and I don't remember where I got it. It could have been from the IJG website, but I'm really not sure. I didn't build it myself, though.

Aaron Reitz

[Edit] Passing -verbose to jpegtran prompts it to display its version info. The standard binary I was using displays this:

Independent JPEG Group's JPEGTRAN, version 9  13-Jan-2013
Copyright (C) 2013, Thomas G. Lane, Guido Vollbeding
[/Edit]

**Comment by MegaByte** [comment]
I see. mozjpegtran has a limitation in the number of scans you can do at once https://github.com/mozilla/mozjpeg/issues/220 , so there's probably something wrong with the logic that splits up the scans into smaller batches that can't handle this many scans at once. You might be able to bypass this for now by editing the $maxperfile variable to be several hundred.

**Comment by Adreitz** [comment]
Okay, I'll give it a try. -b13 is still processing, so I wanted to let it finish to see what happens. It might be related to the issue you mention with the batching of scans, but after a while the periodic scan errors stopped and I got a long run of successful "ticks". Then at some later time (it's hard to see when it happened or how often, due to the number of lines exceeding the terminal history), I started seeing long runs of some new error messages, usually in pairs:

Use of uninitialized value $bsize in addition (+) at C:\Users\17801\Documents\zComp\jpegultrascan-master\jpegultrascan.pl line 303.
Use of uninitialized value $bscans in concatenation (.) or string at C:\Users\17801\Documents\zComp\jpegultrascan-master\jpegultrascan.pl line 303.

and

Use of uninitialized value $size in addition (+) at C:\Users\17801\Documents\zComp\jpegultrascan-master\jpegultrascan.pl line 320.
Use of uninitialized value $scans in concatenation (.) or string at C:\Users\17801\Documents\zComp\jpegultrascan-master\jpegultrascan.pl line 321.

I'll keep testing.

[Edit] -b 13 just finished and, after all that, it spit out a file exactly the same size as -b 3! There are no visible artifacts, so that's good. I'll retry it with $maxperfile set at 400.[/Edit]
[Edit 2] Okay, 400 is too much. I'm getting:
No data returned for:
0 1 2: 0 0 0 9;
0: 1 4 0 9;
0: 1 4 9 8;
0: 1 4 8 7;
0: 1 4 7 6;
0: 1 4 6 5;
0: 1 4 5 4;
0: 1 4 4 3;
0: 1 4 3 2;
0: 1 4 2 1;
0: 1 4 1 0;
0: 5 8 0 9;
0: 5 8 9 8;
0: 5 8 8 7;
0: 5 8 7 6;
0: 5 8 6 5;
0: 5 8 5 4;
0: 5 8 4 3;
0: 5 8 3 2;
0: 5 8 2 1;
0: 5 8 1 0;
0: 9 12 0 9;
0: 9 12 9 8;
0: 9 12 8 7;
0: 9 12 7 6;
0: 9 12 6 5;
0: 9 12 5 4;
0: 9 12 4 3;
0: 9 12 3 2;
0: 9 12 2 1;
0: 9 12 1 0;
0: 13 16 0 9;
0: 13 16 9 8;
0: 13 16 8 7;
0: 13 16 7 6;
0: 13 16 6 5;
0: 13 16 5 4;
0: 13 16 4 3;
0: 13 16 3 2;
0: 13 16 2 1;
0: 13 16 1 0;
0: 17 20 0 9;
0: 17 20 9 8;
0: 17 20 8 7;
0: 17 20 7 6;
0: 17 20 6 5;
0: 17 20 5 4;
0: 17 20 4 3;
0: 17 20 3 2;
0: 17 20 2 1;
0: 17 20 1 0;
0: 21 24 0 9;
0: 21 24 9 8;
0: 21 24 8 7;
0: 21 24 7 6;
0: 21 24 6 5;
0: 21 24 5 4;
0: 21 24 4 3;
0: 21 24 3 2;
0: 21 24 2 1;
0: 21 24 1 0;
0: 25 28 0 9;
0: 25 28 9 8;
0: 25 28 8 7;
0: 25 28 7 6;
0: 25 28 6 5;
0: 25 28 5 4;
0: 25 28 4 3;
0: 25 28 3 2;
0: 25 28 2 1;
0: 25 28 1 0;
0: 29 32 0 9;
0: 29 32 9 8;
0: 29 32 8 7;
0: 29 32 7 6;
0: 29 32 6 5;
0: 29 32 5 4;
0: 29 32 4 3;
0: 29 32 3 2;
0: 29 32 2 1;
0: 29 32 1 0;
0: 33 36 0 9;
0: 33 36 9 8;
0: 33 36 8 7;
0: 33 36 7 6;
0: 33 36 6 5;
0: 33 36 5 4;
0: 33 36 4 3;
0: 33 36 3 2;
0: 33 36 2 1;
0: 33 36 1 0;
0: 37 40 0 9;
0: 37 40 9 8;
0: 37 40 8 7;
0: 37 40 7 6;
0: 37 40 6 5;
0: 37 40 5 4;
0: 37 40 4 3;
0: 37 40 3 2;
0: 37 40 2 1;
0: 37 40 1 0;
0: 41 44 0 9;
0: 41 44 9 8;
0: 41 44 8 7;
0: 41 44 7 6;
0: 41 44 6 5;
0: 41 44 5 4;
0: 41 44 4 3;
0: 41 44 3 2;
0: 41 44 2 1;
0: 41 44 1 0;
0: 45 48 0 9;
0: 45 48 9 8;
0: 45 48 8 7;
0: 45 48 7 6;
0: 45 48 6 5;
0: 45 48 5 4;
0: 45 48 4 3;
0: 45 48 3 2;
0: 45 48 2 1;
0: 45 48 1 0;
0: 49 52 0 9;
0: 49 52 9 8;
0: 49 52 8 7;
0: 49 52 7 6;
0: 49 52 6 5;
0: 49 52 5 4;
0: 49 52 4 3;
0: 49 52 3 2;
0: 49 52 2 1;
0: 49 52 1 0;
0: 53 56 0 9;
0: 53 56 9 8;
0: 53 56 8 7;
0: 53 56 7 6;
0: 53 56 6 5;
0: 53 56 5 4;
0: 53 56 4 3;
0: 53 56 3 2;
0: 53 56 2 1;
0: 53 56 1 0;
0: 57 60 0 9;
0: 57 60 9 8;
0: 57 60 8 7;
0: 57 60 7 6;
0: 57 60 6 5;
0: 57 60 5 4;
0: 57 60 4 3;
0: 57 60 3 2;
0: 57 60 2 1;
0: 57 60 1 0;
0: 61 63 0 9;
0: 61 63 9 8;
0: 61 63 8 7;
0: 61 63 7 6;
0: 61 63 6 5;
0: 61 63 5 4;
0: 61 63 4 3;
0: 61 63 3 2;
0: 61 63 2 1;
0: 61 63 1 0;
Too many scans defined in file C:\Users\[redacted]\AppData\Local\Temp\JnT2opZU53-2316
usage: C:\Users\[redacted]\jpegultrascan-master\mozjpegtran4.0.exe [switches] [inputfile]
...

I'm going to drop it down somewhat and retry.[/Edit 2]

[Edit 3] The "Too many scans" errors seem to go away at about $maxperfile = 100, but I'm still seeing "No data returned for..." as well as a new error that is sometimes, but not always, paired with it: "Bogus virtual array access". Not sure what else to do right now. [/Edit 3]

**Comment by MegaByte** [comment]
Okay, that should be fixed. Thanks for catching.

**Comment by Adreitz** [comment]
Thanks, @MegaByte. The error messages are significantly reduced, but it looks like there is still another bug. Processing the same image from above with -b 13, I got 225 repeats of the "No data returned for:" error, paired with "Missing Huffman code table entry" like as follows:

................................Missing Huffman code table entry

No data returned for:
0 1 2: 0 0 0 9;
0: 1 9 0 2;
0: 1 9 2 1;
0: 1 9 1 0;
0: 10 41 0 2;
.0: 10 41 2 1;
0: 10 41 1 0;
.0: 42 63 0 2;
0: 42 63 2 1;
0: 42 63 1 0;
Missing Huffman code table entry

No data returned for:
0 1 2: 0 0 0 9;
0: 1 9 0 3;
0: 1 9 3 2;
0: 1 9 2 1;
0: 1 9 1 0;
0: 10 41 0 3;
0: 10 41 3 2;
0: 10 41 2 1;
0: 10 41 1 0;
0: 42 63 0 3;
0: 42 63 3 2;
0: 42 63 2 1;
0: 42 63 1 0;
..Missing Huffman code table entry

No data returned for:
0 1 2: 0 0 0 9;
0: 1 9 0 4;
0: 1 9 4 3;
0: 1 9 3 2;
0: 1 9 2 1;
0: 1 9 1 0;
0: 10 41 0 4;
0: 10 41 4 3;
0: 10 41 3 2;
0: 10 41 2 1;
0: 10 41 1 0;
0: 42 63 0 4;
0: 42 63 4 3;
0: 42 63 3 2;
0: 42 63 2 1;
0: 42 63 1 0;
..Missing Huffman code table entry

The error messages seemed restricted to plane 0. The output image was about half the size of the input image and was significantly corrupted when viewed.

**Comment by MegaByte** [comment]
@Adreitz The output you've provided suggests it might be a bug in your version of mozjpegtran. https://github.com/mozilla/mozjpeg/issues/327 e.g. a similar issue was fixed in libjpeg-turbo 2.0.3, which mozjpeg uses: https://github.com/mozilla/mozjpeg/blob/master/ChangeLog.md

If you try not using mozjpeg, does this still occur? I see this on your provided binary of mozjpegtran, but not in my older copy or either version of non-moz jpegtran.

I can add some checks to prevent the output corruption at least.

**Comment by Adreitz** [comment]
Yes, using standard jpegtran for both -p  and -o (the script fails if I only specify -p), it succeeds even with -b 13. I’ll try using an older version of mozjpegtran.

**Comment by MegaByte** [comment]
FYI, this is now fixed in libjpeg-turbo, but it will likely be some time before it makes its way down to mozjpeg.

If you run `set JSIMD_FORCENONE=1` before running jpegultrascan, the error should go away, however.

**Comment by Adreitz** [comment]
Mozjpegtran 3.2 worked without error with -b 13 and setting the environmental variable allowed v.4.0 to work as well. I also found that the output using IJG jpegtran v.9d is a few bytes smaller than the v.9 that I was using. Thanks for looking into all of these issues!
