### ISSUE TITLE
Invalid progressive parameters at scan script entry 3

### ISSUE THREAD

**Issue by Adreitz** [MegaByte/jpegultrascan#3]
I just received a new error message I have never seen before. This is consistent with a particular file. The image appears intact when I view it in an image viewer, but jpegultrascan throws the error message "Invalid progressive parameters at scan script entry 3" near the end of searching the DC scans, bailing out and just creating a copy of the original image instead of an optimized file.

This is the original image (from the Tellurion comic project by Matt Rhodes):
![tellurion_032_by_mattrhodesart-dbc3cy1](https://user-images.githubusercontent.com/11577741/46013232-a5dc2f00-c099-11e8-8c17-bd7783615de1.jpg)

I also tried processing the file through mozjpegtran first, thinking that might clear up whatever issue is causing the problem. This produced a smaller file, as expected, but jpegultrascan still runs into the same issue.

I'm running the current version of jpegultrascan on OS X 10.13.6 with perl 5.26.1 and a combination of the jpeg 9c version of jpegtran and mozjpegtran 3.0 (I think) using the -p and -o switches.

**Comment by MegaByte** [comment]
Sorry @Adreitz, I didn't see your tickets until now. I'll take a look.

**Comment by MegaByte** [comment]
@Adreitz I haven't been able to reproduce, but based on your description, my guess is that this was fixed in 1.3.1. Let me know if you still run into it.
