### ISSUE TITLE
last change to jpegdropscan.pl broke it

### ISSUE THREAD

**Issue by RamKromberg** [MegaByte/jpegultrascan#5]
The last change (for #4) left ``jpegdropscan.pl`` broken: https://github.com/MegaByte/jpegultrascan/commit/e6faeebf3801b99c085a2db9603f4a896e05f4bf#diff-e3cc7d9d07703eae84b352ab726e8d665d426b6a8eabc4e4a01e98ab704e43c7R116-R122

After reverting the change with ``git checkout d3744f292421e77870ef3b315d1217083300ccdb -- jpegdropscan.pl`` it works again.

Btw, I think you forgot to initialize ``$quality`` with the (default per the docs) 0 as it gets pretty noisy when running without ``-d 0``.

p.s. How do jpegdropscan and guetzli differ? Like, jpegultrascan obviously compresses better than jpegrescan but it takes much longer. However, when it comes to jpegdropscan, reading the [guetzli paper](https://arxiv.org/abs/1703.04421) make it seem they're doing about the same thing: "optimizes both the JPEG global quantization tables and the DCT coefficient values in each JPEG block using a closed-loop optimizer" Practically speaking, is there an advantage to using one over the next?

Thanks.

**Comment by MegaByte** [comment]
Thanks for catching that.

jpegdropscan strictly tries to eliminate entire DCT coefficients that influence perceptual quality the least but does so without  changing any quantization and coefficients at the block level. It was an exercise to see what could be done without processing individual blocks, just dropping existing data. guetzli doesn't support outputting progressive images, so you can run it after guetzli+jpegultrascan to squeeze a tiny bit more out at a given quality target.
